# Generated by Django 5.1.7 on 2025-03-19 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('ambulance_type', models.CharField(choices=[('basic', 'Basic ambulance'), ('medical', 'Ambulance with medical assistance')], max_length=10)),
                ('vehicle_type', models.CharField(choices=[('van', 'Van'), ('minibus', 'Minibus'), ('traveller', 'Traveller')], max_length=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.driver')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.hospital')),
            ],
        ),
    ]
